name: union_pay
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  workmanager:
    git:
      url: https://github.com/sunalwaysknows/flutter_workmanager
      ref: f37742bcf612c51e9571d623138a21a90a5992ea

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  scaled_list: ^2.0.0
  table_calendar: ^3.0.6
  get: ^4.6.5
  pin_input_text_field: ^4.5.0
  pin_code_fields: ^7.4.0
  auto_route: ^5.0.4
  auto_route_generator: 5.0.3
  build_runner: ^2.3.3
  pull_to_refresh: ^2.0.0
  http: ^1.2.0
  event_bus: ^2.0.0
  url_launcher: ^6.1.11
  shared_preferences: ^2.0.7
  flutter_screenutil: 5.8.4
  flutter_easyloading: ^3.0.3
  oktoast: 3.3.1
  pinput: ^3.0.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  device_info: ^2.0.0
  package_info: ^2.0.0
  platform_device_id: ^1.0.1
  cached_network_image: 3.3.1
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.6
  dio_cookie_manager: ^2.0.0
  pretty_dio_logger: ^1.1.1
  logger: ^1.1.0
  firebase_core: 2.14.0
  firebase_messaging: 14.6.4
  mutex: ^3.0.1
  shimmer: ^3.0.0
  vibration: 1.8.4
  phone_number: 1.0.0
  photo_manager: 3.0.0-dev.5
  image_picker: 1.0.7
  image: ^3.0.2
  expandable: ^5.0.1
  wechat_assets_picker: 9.0.0-dev.2
  grouped_list: ^5.1.2
  flutter_datetime_picker_plus: ^2.1.0
  share: ^2.0.1
  custom_pop_up_menu:
    path: ./custom_packages/custom_pop_up_menu-1.2.3+1
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

  flutter_plugin_record_plus:
    path: ./custom_packages/flutter_plugin_record_plus-0.0.8
  wecloudchatkit_flutter:
    path: ./custom_packages/WeCloudChatKit_flutter

  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/country_code_info.json
    - assets/data/country_dial_info.json
    - images/cambodia_flag.png
    - images/card_ic.png
    - images/card_selected_ic.png
    - images/chinese_flag.png
    - images/english_flag.png
    - images/hide_eye.png
    - images/home_logo.png
    - images/ic_apply_card_rejected.png
    - images/ic_apply_card_tip2_icon.png
    - images/ic_apply_card_tip_icon.png
    - images/ic_apply_card_under_review.png
    - images/ic_bank_card_done.png
    - images/ic_card_activated.png
    - images/ic_card_camera.png
    - images/ic_card_config_icon.png
    - images/ic_card_favorite_add.png
    - images/ic_card_favorite_delete.png
    - images/ic_card_favorite_edit.png
    - images/ic_card_favorte_no_list.png
    - images/ic_card_front_icon.png
    - images/ic_card_history_calendar.png
    - images/ic_card_manager_favorite.png
    - images/ic_card_manager_freeze.png
    - images/ic_card_manager_rename.png
    - images/ic_card_manager_time_limit.png
    - images/ic_card_passport.png
    - images/ic_card_rename_prefix.png
    - images/ic_card_visible_v2.png
    - images/ic_failure_80.webp
    - images/ic_favorite_no_list_add.png
    - images/ic_floating_new_card.png
    - images/ic_freeze_24.webp
    - images/ic_freeze_80.webp
    - images/ic_manager_cvv.png
    - images/ic_manager_receipt_history.png
    - images/ic_manager_top_up.png
    - images/ic_manager_transfer.png
    - images/ic_new_card_title.png
    - images/ic_no_card_here.png
    - images/ic_notional_id_card.png
    - images/ic_physical_card.webp
    - images/ic_physical_new_card_icon.png
    - images/ic_prepaid_card.webp
    - images/ic_prepaid_physical.png
    - images/ic_prepaid_unionpay_big.png
    - images/ic_service_provider_master.png
    - images/ic_service_provider_unionpay.png
    - images/ic_service_provider_visa.png
    - images/ic_slider_normal_24.webp
    - images/ic_success_80.webp
    - images/ic_unfreeze_20.webp
    - images/ic_union_pay_classic_logo_icon.png
    - images/ic_virtual_card.webp
    - images/ic_virtual_new_card_icon.png
    - images/ic_warning_54.webp
    - images/icon_pin_lock_v2.webp
    - images/icon_prepaid_unionpay_v2.webp
    - images/icon_prepaid_unionpay_white_v2.webp
    - images/icon_prepaid_upay_v2.webp
    - images/icon_prepaid_virtual_v2.png
    - images/icon_prepaid_warning_v2.webp
    - images/language_ic.png
    - images/login_language_drop_down.png
    - images/login_language_up_icon.png
    - images/logout_ic.png
    - images/new_card_ic.png
    - images/notification_card_ic.png
    - images/notification_read_ic.png
    - images/notification_unread_ic.png
    - images/phone_num_error.png
    - images/profile_ic.png
    - images/profile_selected_ic.png
    - images/select_language_ic.png
    - images/show_eye.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: CreditCard
      fonts:
        - asset: assets/fonts/CreditCard.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: khmer_os_battambong
      fonts:
        - asset: assets/fonts/khmer_os_battambong.ttf
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en