name: wecloudchatkit_flutter_example
description: Demonstrates how to use the wecloudchatkit_flutter plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  wecloudchatkit_flutter:
    # When depending on this package from a real application you should use:
    #   wecloudchatkit_flutter: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  cookie_jar: 3.0.1
  #  Dio HTTP 缓存拦截器
  dio_cache_interceptor: ^3.2.6
  #  Dio的 cookie 管理器
  dio_cookie_manager: ^2.0.0
  #网络日志
  pretty_dio_logger: ^1.1.1
  logger: ^1.1.0

  get: ^4.5.1
  #文件系统上查找常用位置
  path_provider: ^2.0.2
  oktoast: ^3.1.5
  shared_preferences: ^2.0.13
  synchronized: ^3.0.0+2
  pull_to_refresh: ^2.0.0
#  keyboard_visibility: ^0.5.6
  permission_handler: ^9.2.0
  flutter_keyboard_visibility: ^5.2.0
#  flutter_plugin_record: ^1.0.1
  flutter_plugin_record_plus:
    path: ./custom_packages/flutter_plugin_record_plus-0.0.8
  image_picker: ^0.8.4+11
  mime: ^1.0.1
  minio: ^3.5.0
  adaptive_dialog: ^1.5.0+1
  video_player: ^2.3.0

  flutter_webrtc: ^0.9.5

  flutter_sound: ^9.2.10

  audio_session: ^0.1.6

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
